config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root "meetings#index"
  resources :users, only: [:edit, :update]
  resources :meetings, only: [:index, :new, :create, :destroy, :show, :checked] do
    resources :contents, only: [:index, :new, :create]
  end
  get 'contents/:id', to: 'contents#checked'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
  has_one_attached :image

  validates :writing, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :meeting_users
  has_many :users, through: :meeting_users, dependent: :destroy
  has_many :contents, dependent: :destroy
  has_rich_text :content

  validates :title, presence: true
end

app/models/meeting_user.rb
class MeetingUser < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
end

app/models/post.rb
class Post < ApplicationRecord
  # has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :meeting_users
  has_many :meetings, through: :meeting_users
  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :first_name, :last_name, :first_name_kana, :last_name_kana, :company_name])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @content = Content.new
    @meeting = Meeting.find(params[:meeting_id])
    @contents = @meeting.contents.includes(:user)

    @meetings = Meeting.all
  end

  def new
    @content = Content.new
  end

  def create
    @meeting = Meeting.find(params[:meeting_id])
    @content = @meeting.contents.new(contents_params)
    # render json:{ content: @content, user_name: @content.user.name }
    respond_to do |format|
      if @content.save
        ActionCable.server.broadcast 'content_channel', content: @content
        format.html { redirect_to 'contents#index' }
        format.json { render 'index.json.jbuilder', status: :created, location: @content }
        format.js
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def checked
    content = Content.find(params[:id])
    if content.checked
      content.update(checked: false)
    else
      content.update(checked: true)
    end

    item = Content.find(params[:id])
    render json: { content: item }
  end

  private

  def contents_params
    params.require(:content).permit(:writing, :image).merge(user_id: current_user.id, checked: false)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    @meetings = Meeting.all
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    if @meeting.save
      redirect_to root_path
    else
      render :new
    end
  end
  

  def destroy
    meeting = Meeting.find(params[:id])
    meeting.destroy
    redirect_to root_path
  end

  def show
    @meeting = Meeting.find(params[:id])
  end

  def checked
    content = Content.find(params[:id])
    if content.checked
      content.update(checked: false)
    else
      content.update(checked: true)
    end
  end

  private

  def meeting_params
    params.require(:meeting).permit(:title, :content, :time, user_ids: [])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contents/index.html.erb
  <div class="contents-header">
      <%= render "shared/header" %>
  </div>

  <div class="contents-middle">
    <div class="col-2 side-bar-left">
      <div class="create">
      <%= link_to "新規議事録作成", new_meeting_path, class:"btn btn-secondary" %>
      </div>
      <div class="contents-message"><h3>議事録一覧</h3></div>
      <div class="main-name">
        <% current_user.meetings.each do |meeting| %>
        <div class="meeting">
        <%= link_to meeting.title, meeting_contents_path(meeting), class:"btn btn-info" %>
        </div>
       <% end %>
      </div>
    </div>

    <div class="col-8 main-contents">
      内容表示
      <% @meeting.title %>
        <div class="bottom-contents">

          <% @contents.each do |content| %>
            <div class="content_post" data-id=<%= content.id %> data-check=<% content.checked %> data-user-name=<% content.user.name %>>
              <div class="post-left">
                <div class="post-name"></div>
                <div class="post-content"><%= content.writing %></div>
              </div>
              <div class="post-right">
                <div class="post-date"></div>
                <div class="contents">
              </div>
                <%= image_tag content.image.variant(resize:'500x500'), class: 'message-image' if content.image.attached? %>
              </div>
            </div>
          <% end %>
        <div id="new_message"></div>
                        <div id="list">
        </div>
        </div>

     </div>


    <div class="col-2 side-bar-right">
      <div class="right-message">参加者</div>
          <% User.all.each do |user| %>
            <div class="use-name">
              <%= user.name %>
            </div>
          <% end %>
          <div class="timer">
            <form name="timer">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-alarm" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M6.5 0a.5.5 0 0 0 0 1H7v1.07a7.001 7.001 0 0 0-3.273 12.474l-.602.602a.5.5 0 0 0 .707.708l.746-.746A6.97 6.97 0 0 0 8 16a6.97 6.97 0 0 0 3.422-.892l.746.746a.5.5 0 0 0 .707-.708l-.601-.602A7.001 7.001 0 0 0 9 2.07V1h.5a.5.5 0 0 0 0-1h-3zm1.038 3.018a6.093 6.093 0 0 1 .924 0 6 6 0 1 1-.924 0zM8.5 5.5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5zM0 3.5c0 .753.333 1.429.86 1.887A8.035 8.035 0 0 1 4.387 1.86 2.5 2.5 0 0 0 0 3.5zM13.5 1c-.753 0-1.429.333-1.887.86a8.035 8.035 0 0 1 3.527 3.527A2.5 2.5 0 0 0 13.5 1z"/>
</svg>
              <input type="text" value="<%=@meeting.time%>" class="form-control">分
              <input type="text" value=""  class="form-control">秒<br>
              <input type="button" value="スタート" onclick="cntStart()" class="btn btn-dark">
              <input type="button" value="ストップ" onclick="cntStop()"  class="btn btn-dark">
            </form>
          </div>

    </div>
  </div>

  <div class="bottom-form">
    <%= form_with model: [@meeting, @content], id: "form" do |f| %>
      <div class="form-item">
      <%= f.text_field :writing, placeholder: '内容を記載してください', class:'col-8', id:"content"%>
              <label class="form-image btn btn-success">
                <span class="image-file"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-image" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9c0 .013 0 .027.002.04V12l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094L15 9.499V3.5a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm4.502 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
          </svg></span>
      <%= f.file_field :image, id: 'content_image', class: 'hidden ' %>
    </label>
      <%= f.submit '投稿する', id: "submit", class:'contents-writing-btn btn btn-success'%>
      </div>
      <div id="image-list"></div>
      <% end %>
      
  </div>
<script>
var timer1; //タイマーを格納する変数（タイマーID）の宣言


//カウントダウン関数を1000ミリ秒毎に呼び出す関数
function cntStart()
{
  document.timer.elements[2].disabled=true;
  timer1=setInterval("countDown()",1000);
}

//タイマー停止関数
function cntStop()
{
  document.timer.elements[2].disabled=false;
  clearInterval(timer1);
}

//カウントダウン関数
function countDown()
{
  var min=document.timer.elements[0].value;
  var sec=document.timer.elements[1].value;
  
  if( (min=="") && (sec=="") )
  {
    alert("時刻を設定してください");
    reSet();
  }
  else
  {
    if (min=="") min=0;
    min=parseInt(min);
    
    if (sec=="") sec=0;
    sec=parseInt(sec);
    
    tmWrite(min*60+sec-1);
  }
}

//残り時間を書き出す関数
function tmWrite(int)
{
  int=parseInt(int);
  
  if (int<=0)
  {
    reSet();
    alert("会議終了の時間です");
  }
  else
  {
    //残り分数はintを60で割って切り捨てる
    document.timer.elements[0].value=Math.floor(int/60);
    //残り秒数はintを60で割った余り
    document.timer.elements[1].value=int % 60;
  }
}

//フォームを初期状態に戻す（リセット）関数
function reSet()
{
  document.timer.elements[0].value="0";
  document.timer.elements[1].value="0";
  document.timer.elements[2].disabled=false;
  clearInterval(timer1);
}  
</script>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinutesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- <%# Bootstrap↓%> -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">


<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Noto+Sans+JP' rel="stylesheet">


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meetings/index.html.erb
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <%= link_to "minutes.", "/", class: 'navbar-brand' %>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.name, "", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "新規議事録", new_meeting_path, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'ログイン', new_user_session_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to '新規登録', new_user_registration_path, class:"nav-link"%>
          </li>
           <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <header class="masthead" style="background-image: url('<%= asset_path('home-bg.jpg')%>')"> <!--クォンテーション注意-->

    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>minutes.</h1>
            <span class="subheading">ー議事録アプリケーションー</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto", id="meeting-title-all">
        <div class="meeting-title"> ー 議事録一覧 ー</div>
        <% @meetings.each do |meeting| %>
          <div class="post-preview">
            <h2 class="post-title">
              <%= link_to meeting.title, meeting_contents_path(meeting) %>
            </h2>
            <h6 class="post-subtitle">
              <%= link_to "事前共有確認", meeting_path(meeting)%>

              <%if user_signed_in? && meeting.user_ids.include?(current_user.id) %>
                /
                <%= link_to "削除", meeting_path(meeting), method: :delete %>
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
</svg>
                  <% else %>
              <% end %>
            </h6>
                <p class="post-meta">
                  created_at <%=l meeting.created_at%></p>
          </div>
          <hr>
        <% end %>


        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

app/views/meetings/new.html.erb
<div class="wrapper">

  <div class="header">
      <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
          <%= link_to "minutes.", "/", class: 'navbar-brand' %>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to current_user.name, "", class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "新規議事録", new_meeting_path, class: "nav-link" %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to 'ログイン', new_user_session_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to '新規登録', new_user_registration_path, class:"nav-link"%>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
  </div>


  <div class="chat-room-form">
     <h1>新規meeting作成</h1>
    <%=form_with model: @meeting, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :タイトル, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :title, class: 'chat__room_name chat-room-form__input', placeholder: '議事録名を入力してください'%>
      </div>
    </div>

    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :内容, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.rich_text_area :content, class: 'chat__room_name chat-room-form__input', placeholder: '議事録内容を記入してください'%>
      </div>
    </div>

    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :会議時間, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :time, class: 'chat__room_name chat-room-form__input', placeholder: '分数を記入してください'%>分
      </div>
    </div>

    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>共有者</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="meeting[user_ids][]" multiple="multiple">
          <option value=""></option>
            <% User.all.where.not(id: current_user.id).each do |user| %>
             <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>
        <input name="meeting[user_ids][]" type="hidden" value=<%=current_user.id%>>
      </div>
    </div>


    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit "議事録作成", class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

</div>

app/views/meetings/show.html.erb
  <div class="header">
      <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
          <%= link_to "minutes.", "/", class: 'navbar-brand' %>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to current_user.name, "", class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "新規議事録", new_meeting_path, class: "nav-link" %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to 'ログイン', new_user_session_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to '新規登録', new_user_registration_path, class:"nav-link"%>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
  </div>

   <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto", id="meeting-title-all">
        <div class="meeting-title"> ー 事前共有内容 ー</div>
          <div class="post-preview">
            <h3>
              <%= @meeting.title %>
            </h3>
          </div>
          <hr>
  <p>
    <%= @meeting.content %>
  </p>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_header.html.erb
  <div class="header-left">
    <%= link_to image_tag('notePC.png' , size: '50x50'), "/", class: 'header-icon' %>
    minutes
  </div>
  <div class="header-right">
  <% if user_signed_in? %>
    <%= link_to current_user.name, "", class: "user-name" %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout "%>
    <%= link_to "新規議事録", new_meeting_path %>
  <% else %>
    <%= link_to 'ログイン', new_user_session_path, class: "login"%>
    <%= link_to '新規登録', new_user_registration_path, class:"sign-up"%>
  <% end %>
  </div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>